app.aws.path-style-access=true
app.aws.region=us-east-1
app.aws.endpoint=http://localhost:4566
app.aws.access-key=test
app.aws.secret-key=test

app.bucket-name.upload-bucket=streamapp-uploads
app.bucket-name.stream-bucket=streamapp-streams

app.sqs.queue.transcode-complete-queue=video-transcode-complete-backend
