app.ffmpeg.path=/opt/bin/ffmpeg

app.bucket-name.upload-bucket=streamapp-uploads
app.bucket-name.stream-bucket=streamapp-streams

app.sqs.queue.transcode-complete-queue=video-transcode-complete-backend
