spring.application.name=transcode-lambda
spring.main.web-application-type=none

spring.cloud.function.definition=transcodeVideo

app.bucket-name.upload-bucket=to_be_overridden
app.bucket-name.stream-bucket=to_be_overridden
app.ffmpeg.path=/opt/bin/ffmpeg

app.sqs.queue.transcode-complete-queue=to_be_overridden
